import datetime
import random
from django.contrib.auth import get_user_model
from django.http import HttpResponse
from django.utils import timezone
from django_lazifier.apps.data_table.demo_app.models import DemoModel

NAME_SAMPLES = [
    'Jacob',
    'Michael',
    'Ethan',
    'Joshua',
    'Daniel',
    'Alexander',
    'Anthony',
    'William',
    'Christopher',
    'Matthew',
    'Jayden',
    'Andrew',
    'Joseph',
    'David',
    'Noah',
    'Aiden',
    'James',
    'Ryan',
    'Logan',
    'John',
    'Nathan',
    'Elijah',
    'Christian',
    'Gabriel',
    'Benjamin',
    'Jonathan',
    'Tyler',
    'Samuel',
    'Nicholas',
    'Gavin',
    'Dylan',
    'Jackson',
    'Brandon',
    'Caleb',
    'Mason',
    'Angel',
    'Isaac',
    'Evan',
    'Jack',
    'Kevin',
    'Jose',
    'Isaiah',
    'Luke',
    'Landon',
    'Justin',
    'Lucas',
    'Zachary',
    'Jordan',
    'Robert',
    'Aaron',
    'Brayden',
    'Thomas',
    'Cameron',
    'Hunter',
    'Austin',
    'Adrian',
    'Connor',
    'Owen',
    'Aidan',
    'Jason',
    'Julian',
    'Wyatt',
    'Charles',
    'Luis',
    'Carter',
    'Juan',
    'Chase',
    'Diego',
    'Jeremiah',
    'Brody',
    'Xavier',
    'Adam',
    'Carlos',
    'Sebastian',
    'Liam',
    'Hayden',
    'Nathaniel',
    'Henry',
    'Jesus',
    'Ian',
    'Tristan',
    'Bryan',
    'Sean',
    'Cole',
    'Alex',
    'Eric',
    'Brian',
    'Jaden',
    'Carson',
    'Blake',
    'Ayden',
    'Cooper',
    'Dominic',
    'Brady',
    'Caden',
    'Josiah',
    'Kyle',
    'Colton',
    'Kaden',
    'Eli',
    'Miguel',
    'Antonio',
    'Parker',
    'Steven',
    'Alejandro',
    'Riley',
    'Richard',
    'Timothy',
    'Devin',
    'Jesse',
    'Victor',
    'Jake',
    'Joel',
    'Colin',
    'Kaleb',
    'Bryce',
    'Levi',
    'Oliver',
    'Oscar',
    'Vincent',
    'Ashton',
    'Cody',
    'Micah',
    'Preston',
    'Marcus',
    'Max',
    'Patrick',
    'Seth',
    'Jeremy',
    'Peyton',
    'Nolan',
    'Ivan',
    'Damian',
    'Maxwell',
    'Alan',
    'Kenneth',
    'Jonah',
    'Jorge',
    'Mark',
    'Giovanni',
    'Eduardo',
    'Grant',
    'Collin',
    'Gage',
    'Omar',
    'Emmanuel',
    'Trevor',
    'Edward',
    'Ricardo',
    'Cristian',
    'Nicolas',
    'Kayden',
    'George',
    'Jaxon',
    'Paul',
    'Braden',
    'Elias',
    'Andres',
    'Derek',
    'Garrett',
    'Tanner',
    'Malachi',
    'Conner',
    'Fernando',
    'Cesar',
    'Javier',
    'Miles',
    'Jaiden',
    'Alexis',
    'Leonardo',
    'Santiago',
    'Francisco',
    'Cayden',
    'Shane',
    'Edwin',
    'Hudson',
    'Travis',
    'Bryson',
    'Erick',
    'Jace',
    'Hector',
    'Josue',
    'Peter',
    'Jaylen',
    'Mario',
    'Manuel',
    'Abraham',
    'Grayson',
    'Damien',
    'Kaiden',
    'Spencer',
    'Stephen',
    'Edgar',
    'Wesley',
    'Shawn',
    'Trenton',
    'Jared',
    'Jeffrey',
    'Landen',
    'Johnathan',
    'Bradley',
    'Braxton',
    'Ryder',
    'Camden',
    'Roman',
    'Asher',
    'Brendan',
    'Maddox',
    'Sergio',
    'Israel',
    'Andy',
    'Lincoln',
    'Erik',
    'Donovan',
    'Raymond',
    'Avery',
    'Rylan',
    'Dalton',
    'Harrison',
    'Andre',
    'Martin',
    'Keegan',
    'Marco',
    'Jude',
    'Sawyer',
    'Dakota',
    'Leo',
    'Calvin',
    'Kai',
    'Drake',
    'Troy',
    'Zion',
    'Clayton',
    'Roberto',
    'Zane',
    'Gregory',
    'Tucker',
    'Rafael',
    'Kingston',
    'Dominick',
    'Ezekiel',
    'Griffin',
    'Devon',
    'Drew',
    'Lukas',
    'Johnny',
    'Ty',
    'Pedro',
    'Tyson',
    'Caiden',
]

LOREM_IPSUM = """Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel interdum enim, vel posuere metus. Integer tempor
sollicitudin tempor. Maecenas scelerisque in odio sodales tristique. Vivamus auctor vitae mi in posuere. Suspendisse
quis eros vel libero luctus vehicula et a nisl. Etiam ac eleifend mauris, nec lobortis magna. Pellentesque dictum
tincidunt arcu in aliquet. Quisque porta venenatis nisl pulvinar sagittis.
"""


def win_lottery():
    if random.randint(0, 100) > 50:
        return True
    return False


def generate_sample_data(request):
    sample_data = []
    user_model = get_user_model()
    user = user_model.objects.first()
    name_sample_length = len(NAME_SAMPLES) - 1

    date = timezone.now()
    date.replace(second=0, microsecond=0)

    five_min = datetime.timedelta(minutes=5)

    for i in range(1000):
        name = NAME_SAMPLES[random.randint(0, name_sample_length)]
        desc = LOREM_IPSUM if win_lottery() else ''
        gender = 'female' if win_lottery() else 'male'
        pins = random.randint(0, 1000)
        date = date + five_min

        sample_data.append(DemoModel(name=name, description=desc, user=user, gender=gender, pins=pins, modified=date))

    DemoModel.objects.bulk_create(sample_data)

    return HttpResponse('All Done')
